### PR TITLE
Save action view state.

### LINKED ISSUE #566: Collapsible EditText not restoring instance state on rotation
(**NOTE**:  (Mostly) minimal reproduction code here: https://github.com/MichaelSims/CollapsibleActionItemRotationTest/tree/action-bar-sherlock)

Observed on HTC Thunderbolt (2.3.4) using ActionBarSherlock version 4.1.0
##### Steps to reproduce
- Add a collapsible item to the action bar using `android:showAsAction="always|collapseActionView"` and `android:actionLayout` pointing to a layout file containing an EditText
- Expand the action item, enter some text into the EditText field.
- Rotate the device
##### Expected behavior

After rotation, the collapsed/expanded state should be restored, and the EditText action item should remain expanded.  State associated with the EditText (contents, cursor position, etc.) should be maintained.
##### Actual behavior

The collapsed/expanded state is reset, and the collapsible item is collapsed.  Upon expanding the item again, the state of the EditText is gone (empty).

Note that this behavior was also observed in the sample-demos app (Collapsible Action Items sample).  The framework implementation exhibits the expected behavior above on Asus Nexus 7" tablet running Android 4.1.1

Original google groups discussion: https://groups.google.com/forum/#!topic/actionbarsherlock/kZlRLtdZ_4E/discussion

### PR DESCRIPTION
**Pull request by SimonVT**
Closes #566.

### CODE REVIEW

**Comment by SimonVT** [comment]
Not testable on the 2.1 emulator: http://code.google.com/p/android/issues/detail?id=2423
Edit: Ignore this message, it works now.

File: library/src/com/actionbarsherlock/ActionBarSherlock.java [hunk 1]
```diff
@@ -537,6 +537,9 @@ public void dispatchPanelClosed(int featureId, android.view.Menu menu) {}
      */
     public void dispatchDestroy() {}
 
+    public abstract Bundle saveHierarchyState();
+
+    public abstract void restoreHierarchyState(Bundle savedInstanceState);
```
Comment (JakeWharton) [inline library/src/com/actionbarsherlock/ActionBarSherlock.java]: These both should be `void` and prefixed with 'dispatch'. This way all of the logic lives inside of the `ActionBarSherlockCompat` class and reduces duplication in activities.

**Comment by JakeWharton** [comment]
Yeah, can you rename it to match?
